[build]
  publish = "public"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 3000


[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"
